[platformio]
default_envs = esp32

[env:esp32]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_speed = 460800

lib_deps =
    adafruit/Adafruit BMP085 Library
    knolleary/PubSubClient

build_flags =
    -D CORE_DEBUG_LEVEL=3

[env:native]
platform = native
build_src_filter =
    +<fuzzy_controller.cpp>
    -<main.cpp>
    -<bmp180_sensor.cpp>
    -<fan_pwm.cpp>
    -<mqtt_service.cpp>
    -<wifi_service.cpp>
test_filter = test_fuzzy
